version: '2'

services:
  ctest_builder_webapp:
    container_name: ctest_builder
    image: ctest_builder
    restart: always
    build:
      context: .
    ports:
      - "9001:8080"
  ctest_frontend:
    container_name: ctest_frontend
    image: ctest_frontend
    restart: always
    build:
      context: ./frontend
    ports:
      - "8000:8080"
