version: '2'

services:
  ctest_backend:
    container_name: ctest_backend
    image: ctest_backend
    restart: always
    build:
      context: ./backend
    ports:
      - "9001:8080"
  ctest_frontend:
    container_name: ctest_frontend
    image: ctest_frontend
    restart: always
    build:
      context: ./frontend
    ports:
      - "8000:8080"
